name: Move HTML Files

on:
  push:
    branches:
      - '**'
  workflow_dispatch:

jobs:
  move-html:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Move HTML files from root to subdirectory
        run: |
          # Enable nullglob so that the pattern expands to nothing if no .html files are found
          shopt -s nullglob
          found=false
          for file in *.html; do
            if [ -f "$file" ]; then
              echo "Processing $file"
              # Remove the .html extension to get the basename
              basename="${file%.html}"
              # Create the subdirectory if it doesn't exist
              mkdir -p "$basename"
              # Move the file to the new location as index.html
              mv "$file" "$basename/index.html"
              found=true
            fi
          done
          if [ "$found" = true ]; then
            echo "HTML files moved. Committing changes."
            git config --global user.name "github-actions[bot]"
            git config --global user.email "github-actions[bot]@users.noreply.github.com"
            git add .
            git commit -m "Move HTML files to subdirectory index.html"
            git push
          else
            echo "No HTML files found in root."
          fi
