name: Move HTML Files and Trigger README Check

on:
  push:
    branches:
      - '**'
  workflow_dispatch:

jobs:
  move-html:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Move HTML files from root to subdirectory
        run: |
          shopt -s nullglob
          found=false
          for file in *.html; do
            if [ -f "$file" ]; then
              echo "Processing $file"
              # Remove the .html extension to get the basename
              base="${file%.html}"
              # Create the subdirectory if it doesn't exist
              mkdir -p "$base"
              # Move the file to the subdirectory as index.html
              mv "$file" "$base/index.html"
              found=true
            fi
          done
          if [ "$found" = true ]; then
            echo "HTML files moved."
          else
            echo "No HTML files found in root."
          fi

      - name: Commit changes if any
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          if ! git diff --cached --quiet; then
            git commit -m "Move HTML files to subdirectory index.html"
            git push
          else
            echo "No changes to commit."
          fi

      - name: Trigger README Check Workflow
        env:
          REPO: ${{ github.repository }}
          PAT: ${{ secrets.PAT }}
        run: |
          echo "Triggering repository dispatch event for README check..."
          curl -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${PAT}" \
            https://api.github.com/repos/${REPO}/dispatches \
            -d '{"event_type": "trigger-readme-check"}'
