name: Check and Update Subfolder READMEs

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Update README files based on template
        run: |
          echo "Scanning for subfolders..."
          # Loop through each non-hidden subdirectory in the repository root
          for dir in $(find . -mindepth 1 -maxdepth 1 -type d -not -path '*/\.*'); do
            folder=$(basename "$dir")
            readme_file="$dir/README.md"
            main_link="https://jp.sakurapy.com/$folder"
            
            # Build the template string using \n for line breaks
            template="# ${folder} Documentation\n\n[Main Link](${main_link})\n\n## Subfiles"
            
            # Append subfile links for each file except README.md and index.html
            for file in "$dir"/*; do
              if [ -f "$file" ]; then
                filename=$(basename "$file")
                if [ "$filename" != "README.md" ] && [ "$filename" != "index.html" ]; then
                  template="${template}\n- [${filename}](${main_link}/${filename})"
                fi
              fi
            done

            # Emit a notice if there is an "index" file (without extension) but no "index.html"
            if [ -f "$dir/index" ] && [ ! -f "$dir/index.html" ]; then
              echo "NOTICE: In folder '$dir', found 'index' but not 'index.html'"
            fi

            # Create or update README.md if its content does not exactly match the template
            if [ ! -f "$readme_file" ]; then
              echo "Creating $readme_file with template content"
              echo -e "$template" > "$readme_file"
            else
              current=$(cat "$readme_file")
              # Compare current content with template (interpreted with echo -e)
              if [ "$current" != "$(echo -e "$template")" ]; then
                echo "Updating $readme_file to match the template"
                echo -e "$template" > "$readme_file"
              else
                echo "$readme_file already matches the template."
              fi
            fi
          done

      - name: Commit changes if any
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add .
          if ! git diff --cached --quiet; then
            git commit -m "Update README.md files to match template [skip ci]"
            git push
          else
            echo "No changes to commit."
          fi
