name: Check and Update Subfolder READMEs

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Update README files based on template
        run: |
          echo "Scanning for subfolders..."
          # Loop through each non-hidden subdirectory in the repository root
          for dir in $(find . -mindepth 1 -maxdepth 1 -type d -not -path '*/\.*'); do
            folder=$(basename "$dir")
            readme_file="$dir/README.md"
            main_link="https://jp.sakurapy.com/$folder"
            
            # Set the template: main link and header
            template="# ${folder} Documentation

[Main Link](${main_link})

## Subfiles"
            
            # Loop through files in the folder (non-hidden, not README.md, not index.html)
            for file in "$dir"/*; do
              if [ -f "$file" ]; then
                filename=$(basename "$file")
                if [ "$filename" != "README.md" ] && [ "$filename" != "index.html" ]; then
                  template="${template}"$'\n'"- [${filename}](${main_link}/${filename})"
                fi
              fi
            done

            # Check for presence of "index" file (without extension) when "index.html" is missing
            if [ -f "$dir/index" ] && [ ! -f "$dir/index.html" ]; then
              echo "NOTICE: In folder '$dir', found 'index' but not 'index.html'"
            fi

            # If the README.md doesn't exist or its content doesn't exactly match the template, update it.
            if [ ! -f "$readme_file" ]; then
              echo "Creating $readme_file with template content"
              echo "$template" > "$readme_file"
            else
              current=$(cat "$readme_file")
              if [ "$current" != "$template" ]; then
                echo "Updating $readme_file to match the template"
                echo "$template" > "$readme_file"
              else
                echo "$readme_file already matches the template."
              fi
            fi

          done

      - name: Commit changes if any
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add .
          # Only commit if there are changes
          if ! git diff --cached --quiet; then
            git commit -m "Update README.md files to match template [skip ci]"
            git push
          else
            echo "No changes to commit."
          fi
