name: Check and Update Subfolder READMEs

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Update README files based on template
        run: |
          echo "Scanning for subfolders..."
          # Loop through each non-hidden subdirectory in the repository root
          for dir in $(find . -mindepth 1 -maxdepth 1 -type d -not -path '*/\.*'); do
            folder=$(basename "$dir")
            readme_file="$dir/README.md"
            main_link="https://jp.sakurapy.com/$folder"
            
            # Build the initial template string using \n for newlines
            template="# ${folder} Documentation\n\n[Main Link](${main_link})\n\n## Subfiles"
            
            # Initialize subfiles and warnings sections
            subfiles=""
            warnings=""
            
            # Iterate over each file in the subfolder
            for file in "$dir"/*; do
              if [ -f "$file" ]; then
                filename=$(basename "$file")
                # Append to subfiles if not README.md and not index.html
                if [ "$filename" != "README.md" ] && [ "$filename" != "index.html" ]; then
                  subfiles="${subfiles}\n- [${filename}](${main_link}/${filename})"
                fi
                # Append a warning for every file (except README.md) that doesn't have a .html extension
                if [ "$filename" != "README.md" ] && [[ "$filename" != *.html ]]; then
                  warnings="${warnings}\n- WARNING: '${filename}' does not have a .html extension"
                fi
              fi
            done
            
            # Append the subfiles list to the template
            template="${template}${subfiles}\n\n## Warnings"
            # If there are no warnings, note that explicitly
            if [ -z "$warnings" ]; then
              warnings="\nNone"
            fi
            template="${template}${warnings}"
            
            # Create or update README.md if its content does not exactly match the generated template
            if [ ! -f "$readme_file" ]; then
              echo "Creating $readme_file with template content"
              echo -e "$template" > "$readme_file"
            else
              current=$(cat "$readme_file")
              if [ "$current" != "$(echo -e "$template")" ]; then
                echo "Updating $readme_file to match the template"
                echo -e "$template" > "$readme_file"
              else
                echo "$readme_file already matches the template."
              fi
            fi
          done

      - name: Commit changes if any
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add .
          if ! git diff --cached --quiet; then
            git commit -m "Update README.md files to match template [skip ci]"
            git push
          else
            echo "No changes to commit."
          fi
